package DesafioClassesiPhone;

public class Loja {
    public static void main(String[] args) {
        iPhone iphone = new iPhone();

        iphone.ligar();
        iphone.atender();
        iphone.iniciarCorreioDeVoz();
        iphone.exibirPagina();
        iphone.atualizarPagina();
        iphone.adicionarNovaPagina();
        iphone.selecionarMusica();
        iphone.pausarMusica();
        iphone.tocarMusica();
    }

}
